%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.0

-ifndef(pb_login).
-define(pb_login, true).

-define(pb_login_gpb_version, "4.11.0").

-ifndef('CS_LOGIN_PB_H').
-define('CS_LOGIN_PB_H', true).
-record(cs_login,
        {account                :: iodata() | undefined, % = 1
         aid                    :: iodata() | undefined % = 2
        }).
-endif.

-endif.
